#!/bin/bash
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.
#       
#       by Ibnu Yahya <ibnu.yahya@toroo.org>


DATE=`date '+%d.%m.%Y'`
ARC=`uname -m`
VERSION="1.0.1"
TOROOBUILD="build/usr"

mkdir -p $TOROOBUILD
mkdir -p $TOROOBUILD/share/tcpanel/
mkdir -p $TOROOBUILD/share/applications/
mkdir -p $TOROOBUILD/sbin/
cp -R -L src/* $TOROOBUILD/share/tcpanel
cp -R -L src/launcher/tcpanel.desktop $TOROOBUILD/share/applications/
cp -R -L src/bin/tcpanel $TOROOBUILD/sbin/
cd build/
PWD=`pwd |sed "s/build//g"`

makepkg $PWD/tcpanel-$VERSION-$ARC-toroo-$DATE.tlz
md5sum $PWD/tcpanel-$VERSION-$ARC-toroo-$DATE.tlz >$PWD/tcpanel-$VERSION-$ARC-toroo-$DATE.md5
